<?php
/*
 * myblock module
 */

 // implements hook_permission
 function myblock_permission() {
  return array(
    'access mypage' => array(
      'title' => t('Access my page'),
      'description' => t('Access my page on my site....'),
    ),
  );
}
 
 // Implements hook_menu()
   function myblock_menu() {
    $items['mypage'] = array(
      'title' => 'My page',
      'type' => MENU_NORMAL_ITEM,
      'page callback' => 'myblock_mypage',
      'access arguments' => array('access mypage'),
      //'page arguments' => array(1, 'foo'),
    );
    return $items;
  }
  /*
   * callback for hook_menu
   */
  function myblock_mypage() {
    return '<b> this is a test <b>';
  }
  
  
  
  
 function myblock_block_info() {
 
  $blocks['myblock'] = array(
    'info' => t('My custom block'),
    // DRUPAL_CACHE_PER_ROLE will be assumed.
  );

  return $blocks;
}
 
function myblock_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'myblock':
      $block['subject'] = t('This is my custom block');
      $block['content'] = '<b>Test</b>'; //can just use html
      break;

  }
  return $block;
}